//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Psi3_WPF.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Psi3_WPF.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .fa-0:before {
        ///    content: &quot;\30&quot;
        ///}
        ///.fa-1:before {
        ///    content: &quot;\31&quot;
        ///}
        ///.fa-2:before {
        ///    content: &quot;\32&quot;
        ///}
        ///.fa-3:before {
        ///    content: &quot;\33&quot;
        ///}
        ///.fa-4:before {
        ///    content: &quot;\34&quot;
        ///}
        ///.fa-5:before {
        ///    content: &quot;\35&quot;
        ///}
        ///.fa-6:before {
        ///    content: &quot;\36&quot;
        ///}
        ///.fa-7:before {
        ///    content: &quot;\37&quot;
        ///}
        ///.fa-8:before {
        ///    content: &quot;\38&quot;
        ///}
        ///.fa-9:before {
        ///    content: &quot;\39&quot;
        ///}
        ///.fa-fill-drip:before {
        ///    content: &quot;\f576&quot;
        ///}
        ///.fa-arrows-to-circle:before {
        ///    content: &quot;\e4bd&quot;
        ///}
        ///.fa-chevron-circl [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string css {
            get {
                return ResourceManager.GetString("css", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {
        ///  &quot;EgressRegion&quot;: &quot;&quot;,
        ///  &quot;ListenInterface&quot;: &quot;any&quot;,
        ///  &quot;LocalHttpProxyPort&quot;: 0,
        ///  &quot;LocalSocksProxyPort&quot;: 0,
        ///  &quot;NetworkLatencyMultiplierLambda&quot;: 0.10000000000000001,
        ///  &quot;ObfuscatedServerListRootURLs&quot;: [
        ///    {
        ///      &quot;OnlyAfterAttempts&quot;: 0,
        ///      &quot;SkipVerify&quot;: false,
        ///      &quot;URL&quot;: &quot;aHR0cHM6Ly9zMy5hbWF6b25hd3MuY29tL3BzaXBob24vd2ViL21qcjQtcDIzci1wdXdsL29zbA==&quot;
        ///    },
        ///    {
        ///      &quot;OnlyAfterAttempts&quot;: 2,
        ///      &quot;SkipVerify&quot;: true,
        ///      &quot;URL&quot;: &quot;aHR0cHM6Ly93d3cudWx0aW1hdGVzdHNhdGFwZXguY29tL3dlYi9tanI0LXAyM3ItcHV3bC9vc2 [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string psiphon {
            get {
                return ResourceManager.GetString("psiphon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        internal static byte[] server_list {
            get {
                object obj = ResourceManager.GetObject("server_list", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
